# Puedes usar estos métodos para recibir apoyo financiero
# Descomenta los que apliquen

# github: [david-barrera-blend]
# ko_fi: tu-usuario
# buy_me_a_coffee: tu-usuario
# custom: ["https://tu-link-de-donacion"]
